import { TCardProps } from 'components/atom/Card/types'

export const itemData: TCardProps[] = [
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
  {
    image: 'images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    isNew: true,
  },
]
