import type { TCardProps } from 'components/atom/Card/types'

export const promotionItemsData: TCardProps[] = [
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
  {
    image: '/images/soldier.png',
    title: 'Тактичний костюм idoger G3...',
    rate: 4,
    reviwers: 12,
    price: 799,
    oldPrice: 849,
    promotion: 25,
  },
]